// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Explains the AI's last chess move to the user.
 *
 * - explainMove - A function that takes the last move and the current board state and returns an explanation of why the AI made that move.
 * - ExplainMoveInput - The input type for the explainMove function.
 * - ExplainMoveOutput - The return type for the explainMove function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainMoveInputSchema = z.object({
  move: z.string().describe('The last move made by the AI in standard algebraic notation (SAN).'),
  boardState: z.string().describe('The current state of the chessboard in Forsyth–Edwards Notation (FEN).'),
});

export type ExplainMoveInput = z.infer<typeof ExplainMoveInputSchema>;

const ExplainMoveOutputSchema = z.object({
  explanation: z.string().describe('A detailed explanation of why the AI made the move.'),
});

export type ExplainMoveOutput = z.infer<typeof ExplainMoveOutputSchema>;

export async function explainMove(input: ExplainMoveInput): Promise<ExplainMoveOutput> {
  return explainMoveFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainMovePrompt',
  input: {schema: ExplainMoveInputSchema},
  output: {schema: ExplainMoveOutputSchema},
  prompt: `You are a grandmaster chess player explaining the AI's move to an amateur player.

  The AI made the move: {{{move}}}
  The current board state is: {{{boardState}}}

  Explain in detail why the AI made this move. Consider the following:
  * What are the immediate tactical reasons for the move?
  * What are the strategic goals the move is trying to achieve?
  * What are the possible responses from the opponent, and how does the move prepare for them?
  * What are the long-term consequences of the move on the game?
  Limit your response to 200 words.
  `,
});

const explainMoveFlow = ai.defineFlow(
  {
    name: 'explainMoveFlow',
    inputSchema: ExplainMoveInputSchema,
    outputSchema: ExplainMoveOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
