// This is an autogenerated file from Firebase Studio.
// You can find your Firebase configuration in the Firebase console.
export const firebaseConfig = {
  "projectId": "studio-5054159132-36e62",
  "appId": "1:674828595597:web:30a010b0edf24cc3f08dc4",
  "apiKey": "AIzaSyCvGWXK6EuBreZBRqtjrZMHxta94hhRuVc",
  "authDomain": "studio-5054159132-36e62.firebaseapp.com",
  "messagingSenderId": "674828595597"
};
